# Generated by Django 6.0.3 on 2026-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='title',
            field=models.CharField(default='macbook loan', max_length=50),
            preserve_default=False,
        ),
    ]
