# Generated by Django 6.0.3 on 2026-04-03 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_credit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
