# Generated by Django 5.1.15 on 2026-03-07 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.account'),
        ),
    ]
