# Generated by Django 5.1.15 on 2026-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_card_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-solid fa-circle-arrow-down', max_length=100),
        ),
    ]
