# Generated by Django 5.1.15 on 2026-03-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_inboxmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('request', 'Request')], default='system', max_length=10),
        ),
    ]
