# Generated by Django 5.1.15 on 2026-03-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_inboxmessage_amount_inboxmessage_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('request', 'Request'), ('gift', 'Gift')], default='system', max_length=10),
        ),
    ]
