# Generated by Django 5.1.15 on 2026-03-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_inboxmessage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='saving_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
