# Generated by Django 5.1.15 on 2026-03-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_account_saving_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='saving_goal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
