# Generated by Django 6.0.3 on 2026-03-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='base_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
