# Generated by Django 6.0.3 on 2026-03-29 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_base_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('flag', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='currency_type',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='main.currency'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('user', 'currency_type'), name='unique_user_currency'),
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
