# Generated by Django 6.0.3 on 2026-03-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('deposit', 'Top-up'), ('withdraw', 'Consumption')], max_length=20),
        ),
    ]
