# Generated by Django 6.0.3 on 2026-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='type',
            field=models.CharField(choices=[('request', 'Request for funds'), ('gift', 'Gift')], max_length=20),
        ),
    ]
