# Generated by Django 6.0.3 on 2026-04-08 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
        ('main', '0008_account_iban_alter_paymentrequest_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='is_active',
        ),
        migrations.AddField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='main.account'),
        ),
        migrations.AlterField(
            model_name='piggybank',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piggy', to='main.account'),
        ),
    ]
