# Generated by Django 5.1.15 on 2026-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
