# Generated by Django 5.1.15 on 2026-03-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('more', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casino_transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category'),
        ),
    ]
